const char **stringlst = {
    N_("Wide arrow"),
    N_("Wide, rounded arrow"),
    N_("Wide, heavy arrow"),
    N_("Triangle arrow"),
    N_("Stylized triangle arrow"),
    N_("Colored triangle"),
    N_("Dart arrow"),
    N_("Concave triangle arrow"),
    N_("Rounded arrow"),
    N_("Sketched arrow"),
    N_("Arrow tail"),
    N_("Distance start"),
    N_("Distance end"),
    N_("Dot"),
    N_("Square"),
    N_("Diamond"),
    N_("Colored dot"),
    N_("Colored square"),
    N_("Colored diamond"),
    N_("Stop"),
    N_("X"),
    N_("Filled semicircle"),
    N_("Empty semicircle"),
    N_("Curvy cross"),
    N_("Scissors"),
    N_("Club"),
    N_("Razor wire"),
    N_("Ellipsis"),
    N_("Torso"),
    N_("Legs"),
    N_("Red pin"),
    N_("Pencil"),
    N_("Triangle cap"),
    N_("Ribbon cap"),
    N_("Ribbon cap, rounded"),
    N_("Butt cap"),
    N_("Serif cap")
};
